# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  # 1
  desc "Creating a code signing certificate and provisioning profile"
  # 2
  lane :provision do
    # 3
    produce(
      app_name: 'FoodSkout',
      language: 'English',
      app_version: '1.0',
      sku: '123abc'
    )
    # 4
    cert
    # 5
    sigh(force: true)
  end

  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Take screenshots"
  lane :screenshot do
    snapshot
  end

  desc "Create ipa"
  lane :build do
    increment_build_number
    gym
  end

  desc "Upload to App Store"
  lane :upload do
    deliver
  end

  lane :tests do
      run_tests(scheme: "FoodSkoutUITests")
  end

  error do |lane, exception|
  # This block is called if there was an error running a lane.
  end

end
