language: objective-c
osx_image: xcode9

branches:
  only:
    - master

script:
  - Scripts/build.sh

xcode_project: OrderedDictionary.xcodeproj
matrix:
  include:
    - xcode_scheme: OrderedDictionary-Mac
      env:
        - XCODE_SDK=macosx
        - XCODE_ACTION="build test"
        - XCODE_DESTINATION="arch=x86_64"
        - XCODE_PLAYGROUND_TARGET="x86_64-apple-macosx10.10"
    - xcode_scheme: OrderedDictionary-iOS
      env:
        - XCODE_SDK=iphonesimulator
        - XCODE_ACTION="build-for-testing test-without-building"
        - XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 6s,OS=10.1"
